# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-15 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0003_auto_20190215_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('N', 'Not Started'), ('I', 'In Development'), ('D', 'Done')], default='N', max_length=1),
        ),
    ]
