# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_auto_20190215_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
