# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0005_auto_20190218_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(max_length=150),
        ),
    ]
