# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-18 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0008_auto_20190218_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=26),
        ),
    ]
