# Generated by Django 2.0 on 2019-03-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0011_auto_20190319_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='user_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
