# Generated by Django 2.0 on 2019-03-19 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0012_feature_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='user_id',
        ),
    ]
